import styles from './Recipe.module.css'
import Head from 'next/head'
import { useRouter } from 'next/router'
import React, { useEffect, useState } from 'react'
import { apiKey } from '../../firebase'
import { MdOutlineTimer } from 'react-icons/md';
import {  GiMilkCarton, GiWheat } from 'react-icons/gi';

function recipe() {
    const router = useRouter()
    const [detail, setDetail]= useState({})
    let params = router.query

    useEffect(()=>{
        if(params.recipe){
        const fetchDetail = async() =>{
            let res = await fetch(`https://api.spoonacular.com/recipes/${params.recipe}/information?apiKey=${apiKey}`)
            const data = await res.json()
            setDetail(data)
        }
        fetchDetail()}
        
    }, [params.recipe])
    console.log(detail)
  return (
    <>
        <Head>
            <title>What's for dinner</title>
            <meta name="description" content="Generated by create next app" />
            <meta name="viewport" content="width=device-width, initial-scale=1" />
            <link rel="icon" href="/logo.png" />
        </Head>
        <div className={styles.detail}>
            <div className={styles.left}>
                <div className={styles.left_top}>
                    <div className={styles.logo}>
                        <img src='/logo.png' alt="logo"/>
                    </div>
                    <div className={styles.time}>
                        <div className={styles.time_top}>
                            <h1>{detail.readyInMinutes} min</h1>
                        </div>
                        <div className={styles.time_bottom}>
                            <MdOutlineTimer/>
                        </div>
                    </div>
                </div>
                <div className={styles.left_middle}>
                    <div className={styles.left_middle_img}>
                        <img src={detail.image}/>
                    </div>
                </div>
                <div className={styles.left_bottom}>
                    <div className={styles.vegan}>
                        <img src='/vegan.png'/>
                    </div>
                    <div className={styles.vegan_des}>
                        <h1>NOT</h1>
                    </div>
                </div>
            </div>
            <div className={styles.middle}>
                <div className={styles.middle_top}>
                    <div className={styles.instruction}>
                        <h1>instruction</h1>
                    </div>
                    <div className={styles.ingredients}>
                        <h1>ingredients</h1>
                    </div>
                </div>
                <div className={styles.middle_bottom}>
                    <h4  dangerouslySetInnerHTML={{__html: detail.summary}}></h4>
                    <h4  dangerouslySetInnerHTML={{__html: detail.instructions}}></h4>
                </div>
            </div>
            <div className={styles.right}>
                <div className={styles.right_top}>
                    <div className={styles.serving_left}><p>serving</p></div>
                    <div className={styles.serving_right}>{detail.servings}</div>
                </div>
                <div className={styles.right_middle}>
                    <GiMilkCarton/>
                </div>
                <div className={styles.right_bottom}>
                    <GiWheat/>
                </div>
            </div>
        </div>
    </>
  )
}

export default recipe

