import styles from './Recipe.module.css'
import Head from 'next/head'
import { useRouter } from 'next/router'
import React, { useEffect, useState } from 'react'
import { apiKey } from '../../firebase'
import { AiFillHeart, AiOutlineHeart } from 'react-icons/ai';
import {BsDownload, BsPrinter } from 'react-icons/bs'
import {GiKnifeFork} from 'react-icons/gi'
import Nav from '../../components/Nav'

function recipe() {
    const router = useRouter()
    const [activeTab, setActiveTab] = useState("instructions")
    const [detail, setDetail]= useState({})
    let params = router.query
    const hero = [
        "https://images.unsplash.com/photo-1507048331197-7d4ac70811cf?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=1674&q=80",
        "https://images.unsplash.com/photo-1605522469906-3fe226b356bc?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=1744&q=80",
        "https://images.unsplash.com/photo-1671725779253-aa2351eb9271?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=1740&q=80",
        "https://images.unsplash.com/photo-1518291344630-4857135fb581?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=1738&q=80",
        "https://plus.unsplash.com/premium_photo-1661573540859-616d65c2fa68?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=1740&q=80",
        "https://images.unsplash.com/photo-1543353071-873f17a7a088?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=1740&q=80",
        "https://images.unsplash.com/photo-1495461199391-8c39ab674295?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=1740&q=80"
    ]
    function pickRandomItem(items) {
        return items[Math.floor(Math.random() * items.length)];
    }

    const instructions = detail?.instructions?.split('.'); 

    useEffect(()=>{
        if(params.recipe){
        const fetchDetail = async() =>{
            let res = await fetch(`https://api.spoonacular.com/recipes/${params.recipe}/information?apiKey=${apiKey}&includeNutrition=true`)
            const data = await res.json()
            setDetail(data)
        }
        fetchDetail()}
        
    }, [params.recipe])
    console.log(detail)
    function minutesToHoursString(minutes) {
        let hours = Math.floor(minutes / 60);
        let remainingMinutes = minutes % 60;
      
        if (hours === 0) {
          return `${remainingMinutes} min`;
        } else if (remainingMinutes === 0) {
          return `${hours} h`;
        } else {
          return `${hours} h ${remainingMinutes} min`;
        }
      }
  return (
    <>
        <Nav/>
        <Head>
            <title>What's for dinner</title>
            <meta name="description" content="Generated by create next app" />
            <meta name="viewport" content="width=device-width, initial-scale=1" />
            <link rel="icon" href="/logo.png" />
        </Head>
        <div className={styles.detail}>
            {/* <div className={styles.left}>
                <div className={styles.left_top}>
                    <div className={styles.logo}>
                        <a href='/'><img src='/logo.png' alt="logo"/></a>
                    </div>
                    <div className={styles.time}>
                        <div className={styles.time_top}>
                            <h1>{minutesToHoursString(detail.readyInMinutes)}</h1>
                        </div>
                        <div className={styles.time_bottom}>
                            <MdOutlineTimer/>
                        </div>
                    </div>
                </div>
                <div className={styles.left_middle}>
                    <div className={styles.left_middle_img}>
                        <img src={detail.image}/>
                    </div>
                </div>
                <div className={styles.left_bottom}>
                    <div className={styles.vegan}>
                        <img src='/vegan.png'/>
                    </div>
                    <div className={styles.vegan_des}>
                        <h1>{detail.vegan? "yes": "no"}</h1>
                    </div>
                </div>
            </div>
            <div className={styles.middle}>
                <div className={styles.middle_top}>
                    <div className={styles.instruction}>
                        <button
                        onClick={() => setActiveTab('instructions')}
                        className={activeTab === "instructions" ? styles.active: styles.disable}
                        >instruction</button>
                    </div>
                    <div className={styles.ingredients}>
                        <button
                        className={activeTab === "ingredients" ? styles.active: styles.disable}
                        onClick={() => setActiveTab('ingredients')}
                        >ingredients</button>
                    </div>
                </div>
                {activeTab === "instructions" && (
                    <div className={styles.middle_bottom}>
                        <p  dangerouslySetInnerHTML={{__html: detail.summary}}></p>
                        <p  dangerouslySetInnerHTML={{__html: detail.instructions}}></p>
                    </div>
                )}
                {activeTab === "ingredients" && (
                    <ul className={styles.middle_bottom}>
                        {detail.extendedIngredients.map((i)=> (
                        <li key={i.id}>{i.original}</li>) )}
                    </ul>
                )}
            </div>
            <div className={styles.right}>
                <div className={styles.right_top}>
                    <div className={styles.serving_left}><p>serving</p></div>
                    <br/>
                    <div className={styles.serving_right}>{detail.servings}</div>
                </div>
                <div className={styles.right_middle}>
                    <GiMilkCarton/>
                    <h1>{detail.dairyFree? "dairy free" : "contain dairy"}</h1>
                </div>
                <div className={styles.right_bottom}>
                    <GiWheat/>
                    <h1>{detail.glutenFree? "gluten free" : "contain gluten"}</h1>
                </div>
            </div> */}
            <div className={styles.banner}>
                <img src={pickRandomItem(hero)}/>
                <div className={styles.banner_icons}>
                    <div className={styles.banner_icon}><BsPrinter/></div>
                    <div className={styles.banner_icon}><AiOutlineHeart/></div>
                    <div className={styles.banner_icon}><BsDownload/></div>
                </div>
            </div>

            <div className={styles.detail_recipe}>
                <div className={styles.detail_recipe_left}>
                    <div className={styles.summary}>
                        <p dangerouslySetInnerHTML={{__html: detail.summary}}></p>
                    </div>
                    <div className={styles.detail_recipe_ingre}>
                        <div>
                            <h1>Ingredients :</h1>
                        </div>
                        <div>
                            <ol className={styles.ingre_list}>
                                {detail.extendedIngredients?.map((i)=> (
                                <li key={i.id}>{i.original}</li>) )}
                            </ol>
                        </div>
                    </div>

                    <div className={styles.detail_recipe_ingre}>
                        <div>
                            <h1>Direction :</h1>
                        </div>
                        <div>
                            <ol className={styles.ingre_list}>
                                {instructions?.slice(0, -1).map((i, index) => (
                                    <li key={index}>{i}</li>
                                ))}
                            </ol>
                        </div>
                    </div>
                </div>
                
                <div className={styles.detail_recipe_right}>
                    <div className={styles.detail_recipe_name}>
                        <h1>{detail.title}</h1>
                    </div>
                    <div className={styles.detail_recipe_detail}>
                        <ul>
                            <li><GiKnifeFork/> Servings: {detail?.servings}</li>
                            <li><GiKnifeFork/> Ready In: {minutesToHoursString(detail?.readyInMinutes)}</li>
                            <li><GiKnifeFork/> Carbs: {detail?.nutrition?.caloricBreakdown.percentCarbs}%</li>
                            <li><GiKnifeFork/> Fat: {detail?.nutrition?.caloricBreakdown.percentCarbs}%</li>
                            <li><GiKnifeFork/> Protein: {detail?.nutrition?.caloricBreakdown.percentCarbs}%</li>
                        </ul>
                    </div>
                    <div className={styles.detail_recipe_btn}>
                        <button>Nutrition Info</button>
                    </div>
                </div>
            </div>
        </div>
    </>
  )
}

export default recipe

