import Head from 'next/head'
import { Inter } from '@next/font/google'
import Nav from '../components/Nav'
import Search from '../components/Search'
import Footer from '../components/Footer'
import RecipeList from '../components/RecipeList'

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  return (
    <>
      <Head>
        <title>What's for dinner</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/logo.png" />
      </Head>
      <Nav/>
      <RecipeList/>
      <Search/>
      <Footer/>
    </>
  )
}
